//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backbg {
            get {
                object obj = ResourceManager.GetObject("backbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El aire estaba llena de humo, es difficil respirar con tanta contaminacion, grandes nubles de ceniza y vapor cubrian al barco en su enteridad, llegando hasta la caja en la que me escondia
        ///#Pronto oi un silbato, por mientras que el gran barco volador empezo a decender. el llanto del oceano fue remplazado por la harmonia de la cuidad.
        ///#una vez en el puerto, dos rufianes levantaron mi escondite y se lo llevaron, evadiendo ala policia, pusieron mi caja en un caruage y empezaron a manejar.
        ///#Apesar de estar en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..................................
        ///#Es el año 2058, Tuviste una noche pesada como detective privado en Liverpool, Inglaterra.
        ///En eso tocan a tu puerta. 
        ///#Al parecer alguien asesino a tu hermana en Londres esa misma noche. 
        ///Y aquí es donde empieza el juego.
        ///#Llegas al cuarto donde fue asesinada, es un cuarto chico, alfombra morada
        ///una mesita y la cama. Al fondo esta la puerta para ir al baño.
        ///#Es un cuarto elegante, alamenos para estar en una prision
        ///#Nunca estuve cerca con mi hermana, Me fui de la h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ese lugar en cuanto pude, tratando de conseguir aire fresca.
        ///#busque en mis bolsillos y saque mi pipa de opio, un obseqio de my abuelo de las tierras lejanas de Hongkong
        ///#ironica mente, el vapor de pieza es mucho mas limpia que el aire aqui en londres.
        ///#inhale, mesmerizado por los encranes de plate en la pipa de marfil.
        ///#Derepente Todo se volvio Negro, pense que me habia desmallado, hasta que senti el golpe en la nuca.
        /// </summary>
        internal static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Me acerce al &quot;don&quot;, esta tiezo
        ///# &quot;DEjEme ver el cuerpo&quot;
        ///#Don: 
        ///&quot;Alex, tranquilizate&quot;
        ///Se pone enfrente de mi, bloqueando la puerta.
        ///#&quot;Por un demonio, Don, si no me dejas entrar ahi en los siguientes 10 segundos&quot;
        ///Empeze a desenfundar mi arma.
        ///#El simple mente se quedo quieto, sin decir una sola palabra
        ///#Don:
        ///&quot;Se que es difficil, pero necesitamos saber que es lo que tenemos en las manos&quot;
        ///#&quot;Nunca habiamos visto un crimen asi, solo encontramos sus extremidades, el cuerpo no esta&quot;
        ///#Suspiro
        ///#Don:
        ///&quot; n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
    }
}
